FROM node:latest as npm-build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json package-lock.json ./
USER $user
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=npm-build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

